In [ ]:
%load_ext dotenv
%dotenv

# What are we doing?

## Objectives 


* Build a data pipeline that downloads price data from the internet, stores it locally, transforms it into return data, and stores the feature set.
    - Getting the data.
    - Schemas and index in Dask.

* Explore the parquet format.
    - Reading and writing parquet files.
    - Read datasets that are stored in distributed files.
    - Discuss Dask vs. Pandas as a small example of big vs small data.
    
* Discuss the use of environment variables for settings.
* Discuss how to use Jupyter notebooks and source code concurrently. 
* Logging and using a standard logger.

## About the Data

+ We will download the prices for a list of stocks.
+ The source is Yahoo Finance, and the data, along with its description, is available via [Kaggle](https://www.kaggle.com/datasets/jacksoncrow/stock-market-dataset).


## Medallion Architecture

+ The architecture that we are thinking about is called Medallion by [DataBricks](https://www.databricks.com/glossary/medallion-architecture). It is an ELT type of thinking, although our data is well-structured.

<div>
<img src="./images/02_medallion_architecture.png" height=300>
</div>

+ In our case, we would like to optimize the number of times that we download data from the internet. 
+ Ultimately, we will build a pipeline manager class to control the process of obtaining and transforming our data.

<div>
<img src="./images/02_target_pipeline_manager.png" height=250>
</div>

# Download Data

Download the [Stock Market Dataset from Kaggle](https://www.kaggle.com/datasets/jacksoncrow/stock-market-dataset). Note that you may be required to register for a free account. Alternatively, download the file from [this location](https://drive.google.com/drive/folders/1AA4gapDLpI194TGce1bY25sd91Km-tU3?usp=drive_link).

+ Extract stock prices (not ETFs) into the directory: `./05_src/data/prices_csv/`. 
+ To be clear, your folder structure should include the path `05_src/data/prices_csv/stocks`.

The command `%run update_path.py` runs a local script that adds the repository's `../../05_src/` directory to the notebook's kernel path. This way, we can use our modules within the notebook.

In [1]:
%run update_path.py

To load the historical price data for stocks and ETFs, use the code below. Notice the following:

+ Libraries are ordered from high-level to low-level libraries from the package manager. Local modules are imported at the end. 
+ The function `get_logger()` is called with `__name__` as recommended by [Python's documentation](https://docs.python.org/3/howto/logging.html#logging-advanced-tutorial).

In [2]:
from glob import glob
import os
import pandas as pd
import random

from utils.logger import get_logger
_logs = get_logger(__name__)

+ The [`glob` module](https://docs.python.org/3/library/glob.html) is used for finding path names that match specified patterns using Unix shell-style rules.

+ Notice that the module `glob` contains a function called `glob`; therefore, we used `from glob import glob` above.

+ The path in which we are searching for our csv files is produced by joining two strings:



    - The value of the environment variable 'SRC_DIR' that we obtain with `os.getenv('SRC_DIR')` (this variable points to ./05_src).

    - Another string given by "data/prices_csv/stocks/*.csv".

    - Both strings are combined into an OS-consistent path using `os.path.join(...)`.

+ After we know the location of all our files, we sample a subset of them.

In [3]:
stock_files = glob(os.path.join(os.getenv('SRC_DIR'), "data/prices_csv/stocks/*.csv"))
_logs.info(f'Found {len(stock_files)} stock price files.')

random.seed(42)
n_sample = 60
stock_files = random.sample(stock_files, n_sample)
_logs.info(f'Sampled {n_sample} stock price files for processing. The files are: {stock_files   }')

2026-10-19 01:52:43,339, 3619788285.py, 2, INFO, Found 5878 stock price files.
2026-10-19 01:52:43,341, 3619788285.py, 7, INFO, Sampled 60 stock price files for processing. The files are: ['../../05_src/data/prices_csv/stocks\\TOCA.csv', '../../05_src/data/prices_csv/stocks\\CBLI.csv', '../../05_src/data/prices_csv/stocks\\ALGR.csv', '../../05_src/data/prices_csv/stocks\\GLEO.csv', '../../05_src/data/prices_csv/stocks\\FLDM.csv', '../../05_src/data/prices_csv/stocks\\ETR.csv', '../../05_src/data/prices_csv/stocks\\CMO.csv', '../../05_src/data/prices_csv/stocks\\BXMT.csv', '../../05_src/data/prices_csv/stocks\\VIIX.csv', '../../05_src/data/prices_csv/stocks\\RENN.csv', '../../05_src/data/prices_csv/stocks\\BMA.csv', '../../05_src/data/prices_csv/stocks\\SMMC.csv', '../../05_src/data/prices_csv/stocks\\MOS.csv', '../../05_src/data/prices_csv/stocks\\AMN.csv', '../../05_src/data/prices_csv/stocks\\AMCI.csv', '../../05_src/data/prices_csv/stocks\\BR.csv', '../../05_src/data/prices_csv/stocks\\EROS.csv', '../../05_src/data/prices_csv/stocks\\FAT.csv', '../../05_src/data/prices_csv/stocks\\PFIS.csv', '../../05_src/data/prices_csv/stocks\\SR.csv', '../../05_src/data/prices_csv/stocks\\ALNA.csv', '../../05_src/data/prices_csv/stocks\\RUSHA.csv', '../../05_src/data/prices_csv/stocks\\EBAYL.csv', '../../05_src/data/prices_csv/stocks\\ZNH.csv', '../../05_src/data/prices_csv/stocks\\TTD.csv', '../../05_src/data/prices_csv/stocks\\WTFCM.csv', '../../05_src/data/prices_csv/stocks\\RELV.csv', '../../05_src/data/prices_csv/stocks\\MNR.csv', '../../05_src/data/prices_csv/stocks\\ESP.csv', '../../05_src/data/prices_csv/stocks\\NGHCZ.csv', '../../05_src/data/prices_csv/stocks\\SMBK.csv', '../../05_src/data/prices_csv/stocks\\GMED.csv', '../../05_src/data/prices_csv/stocks\\ACRX.csv', '../../05_src/data/prices_csv/stocks\\CSU.csv', '../../05_src/data/prices_csv/stocks\\WPP.csv', '../../05_src/data/prices_csv/stocks\\MPAA.csv', '../../05_src/data/prices_csv/stocks\\IRCP.csv', '../../05_src/data/prices_csv/stocks\\GMDA.csv', '../../05_src/data/prices_csv/stocks\\CROX.csv', '../../05_src/data/prices_csv/stocks\\EPC.csv', '../../05_src/data/prices_csv/stocks\\INTL.csv', '../../05_src/data/prices_csv/stocks\\BXC.csv', '../../05_src/data/prices_csv/stocks\\BPTH.csv', '../../05_src/data/prices_csv/stocks\\LILA.csv', '../../05_src/data/prices_csv/stocks\\BSBK.csv', '../../05_src/data/prices_csv/stocks\\KBH.csv', '../../05_src/data/prices_csv/stocks\\ITP.csv', '../../05_src/data/prices_csv/stocks\\SRL.csv', '../../05_src/data/prices_csv/stocks\\GBLIZ.csv', '../../05_src/data/prices_csv/stocks\\AR.csv', '../../05_src/data/prices_csv/stocks\\NR.csv', '../../05_src/data/prices_csv/stocks\\QTRX.csv', '../../05_src/data/prices_csv/stocks\\CHCI.csv', '../../05_src/data/prices_csv/stocks\\LGC.csv', '../../05_src/data/prices_csv/stocks\\BHAT.csv', '../../05_src/data/prices_csv/stocks\\RJZ.csv', '../../05_src/data/prices_csv/stocks\\GWGH.csv', '../../05_src/data/prices_csv/stocks\\TENB.csv', '../../05_src/data/prices_csv/stocks\\SZC.csv', '../../05_src/data/prices_csv/stocks\\KFY.csv']

We load the sampled files into dataframes and concatenate them:

+ Start with an empty list.
+ Read each file into a dataframe and [`append()` it to the list](https://docs.python.org/3/tutorial/datastructures.html#more-on-lists). Notice that `append()` is an in-place operation (it does not return a list, it modifies the list in place).
+ Finally, we concatenate all dataframes along the vertical axis (`axis=0`) using [`pd.concat()`](https://pandas.pydata.org/docs/user_guide/merging.html#concat). 
+ Notice that we do not concatenate each time that we load a dataframe. According to [Panda's documentation](https://pandas.pydata.org/docs/user_guide/merging.html#concat): 

> "`concat()` makes a full copy of the data, and iteratively reusing `concat()` can create unnecessary copies. Collect all DataFrame or Series objects in a list before using `concat()`."

In [4]:
dt_list = []
for s_file in stock_files:
    _logs.info(f"Reading file: {s_file}")
    dt = pd.read_csv(s_file).assign(
        source = os.path.basename(s_file),
        ticker = os.path.basename(s_file).replace('.csv', ''),
        Date = lambda x: pd.to_datetime(x['Date'])
    )
    dt_list.append(dt)
stock_prices = pd.concat(dt_list, axis = 0, ignore_index = True)

2026-10-19 01:52:46,990, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\TOCA.csv
2026-10-19 01:52:47,080, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\CBLI.csv
2026-10-19 01:52:47,119, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\ALGR.csv
2026-10-19 01:52:47,139, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\GLEO.csv
2026-10-19 01:52:47,148, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\FLDM.csv
2026-10-19 01:52:47,184, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\ETR.csv
2026-10-19 01:52:47,218, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\CMO.csv
2026-10-19 01:52:47,254, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\BXMT.csv
2026-10-19 01:52:47,282, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\VIIX.csv
2026-10-19 01:52:47,313, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\RENN.csv
2026-10-19 01:52:47,351, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\BMA.csv
2026-10-19 01:52:47,375, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\SMMC.csv
2026-10-19 01:52:47,396, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\MOS.csv
2026-10-19 01:52:47,423, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\AMN.csv
2026-10-19 01:52:47,455, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\AMCI.csv
2026-10-19 01:52:47,473, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\BR.csv
2026-10-19 01:52:47,498, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\EROS.csv
2026-10-19 01:52:47,517, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\FAT.csv
2026-10-19 01:52:47,534, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\PFIS.csv
2026-10-19 01:52:47,554, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\SR.csv
2026-10-19 01:52:47,602, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\ALNA.csv
2026-10-19 01:52:47,617, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\RUSHA.csv
2026-10-19 01:52:47,661, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\EBAYL.csv
2026-10-19 01:52:47,676, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\ZNH.csv
2026-10-19 01:52:47,703, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\TTD.csv
2026-10-19 01:52:47,738, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\WTFCM.csv
2026-10-19 01:52:47,767, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\RELV.csv
2026-10-19 01:52:47,808, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\MNR.csv
2026-10-19 01:52:47,840, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\ESP.csv
2026-10-19 01:52:47,875, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\NGHCZ.csv
2026-10-19 01:52:47,890, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\SMBK.csv
2026-10-19 01:52:47,931, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\GMED.csv
2026-10-19 01:52:47,951, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\ACRX.csv
2026-10-19 01:52:47,977, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\CSU.csv
2026-10-19 01:52:48,000, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\WPP.csv
2026-10-19 01:52:48,037, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\MPAA.csv
2026-10-19 01:52:48,061, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\IRCP.csv
2026-10-19 01:52:48,091, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\GMDA.csv
2026-10-19 01:52:48,110, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\CROX.csv
2026-10-19 01:52:48,139, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\EPC.csv
2026-10-19 01:52:48,166, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\INTL.csv
2026-10-19 01:52:48,199, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\BXC.csv
2026-10-19 01:52:48,224, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\BPTH.csv
2026-10-19 01:52:48,247, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\LILA.csv
2026-10-19 01:52:48,263, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\BSBK.csv
2026-10-19 01:52:48,276, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\KBH.csv
2026-10-19 01:52:48,297, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\ITP.csv
2026-10-19 01:52:48,330, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\SRL.csv
2026-10-19 01:52:48,368, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\GBLIZ.csv
2026-10-19 01:52:48,385, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\AR.csv
2026-10-19 01:52:48,414, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\NR.csv
2026-10-19 01:52:48,448, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\QTRX.csv
2026-10-19 01:52:48,468, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\CHCI.csv
2026-10-19 01:52:48,489, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\LGC.csv
2026-10-19 01:52:48,515, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\BHAT.csv
2026-10-19 01:52:48,535, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\RJZ.csv
2026-10-19 01:52:48,564, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\GWGH.csv
2026-10-19 01:52:48,584, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\TENB.csv
2026-10-19 01:52:48,610, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\SZC.csv
2026-10-19 01:52:48,647, 2577063914.py, 3, INFO, Reading file: ../../05_src/data/prices_csv/stocks\KFY.csv

Verify the structure of the `stock_prices` data using the [`info()` dataframe method](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html):

In [5]:
stock_prices.info()

<class 'pandas.DataFrame'>
RangeIndex: 225036 entries, 0 to 225035
Data columns (total 9 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   Date       225036 non-null  datetime64[us]
 1   Open       225034 non-null  float64
 2   High       225034 non-null  float64
 3   Low        225034 non-null  float64
 4   Close      225034 non-null  float64
 5   Adj Close  225034 non-null  float64
 6   Volume     225034 non-null  float64
 7   source     225036 non-null  str
 8   ticker     225036 non-null  str
dtypes: datetime64[us](1), float64(6), str(2)
memory usage: 17.8 MB

We can subset our ticker data set using standard indexing techniques. Good references for this type of data manipulation are:

+ [Panda's Documentation](https://pandas.pydata.org/docs/user_guide/indexing.html#indexing-and-selecting-data). 
+ [Panda's Cookbook](https://pandas.pydata.org/docs/user_guide/cookbook.html#cookbook-selection).

From the subset data frame, select one column and convert to list.

In [6]:
select_tickers = stock_prices['ticker'].unique().tolist()
select_tickers

['TOCA',
 'CBLI',
 'ALGR',
 'GLEO',
 'FLDM',
 'ETR',
 'CMO',
 'BXMT',
 'VIIX',
 'RENN',
 'BMA',
 'SMMC',
 'MOS',
 'AMN',
 'AMCI',
 'BR',
 'EROS',
 'FAT',
 'PFIS',
 'SR',
 'ALNA',
 'RUSHA',
 'EBAYL',
 'ZNH',
 'TTD',
 'WTFCM',
 'RELV',
 'MNR',
 'ESP',
 'NGHCZ',
 'SMBK',
 'GMED',
 'ACRX',
 'CSU',
 'WPP',
 'MPAA',
 'IRCP',
 'GMDA',
 'CROX',
 'EPC',
 'INTL',
 'BXC',
 'BPTH',
 'LILA',
 'BSBK',
 'KBH',
 'ITP',
 'SRL',
 'GBLIZ',
 'AR',
 'NR',
 'QTRX',
 'CHCI',
 'LGC',
 'BHAT',
 'RJZ',
 'GWGH',
 'TENB',
 'SZC',
 'KFY']

# Storing Data in CSV

+ We have some data. How do we store it?
+ We can compare two options, CSV and Parquet, by measuring their performance:

    - Time to save: We will measure time by using the `time` library.
    - Space required on drive: We will use the custom function below.

In [7]:
def get_dir_size(path='.'):
    '''Returns the total size of files contained in path.'''
    total = 0
    with os.scandir(path) as it:
        for entry in it:
            if entry.is_file():
                total += entry.stat().st_size
            elif entry.is_dir():
                total += get_dir_size(entry.path)
    return total

Load the specification of a temporary directory from the environment  and create a subdirectory in it called "csv":

+ Use `os.getenv("TEMP_DATA")` to obtain the desired location of the temporary folder from an environment variable.
+ If the subdirectory exists, delete it using `shutil.rmtree()`; the flag `ignore_errors=True` helps us in case the subdirectory does not exist (for instance, in the first run).
+ Create a directory with path given by `csv_dir` using `os.makedirs()`; the flag `exist_ok=True` indicates that if the directory already exists, then the function will do nothing.
+ Finally, create the stock price file location, `stock_csv`, which will be used to create the csv file.

In [8]:
import shutil

temp = os.getenv("TEMP_DATA")
csv_dir = os.path.join(temp, "csv")

shutil.rmtree(csv_dir, ignore_errors=True)
os.makedirs(csv_dir, exist_ok=True)
stock_csv = os.path.join(csv_dir, "stock_px.csv")

Save the concatenated dataframe to a CSV file. We measure the time elapsed by storing the start and end times, then we calculate their difference in seconds.

In [9]:
import time

start = time.time()
stock_prices.to_csv(stock_csv, index = False)
end = time.time()

_logs.info(f'Writing data ({stock_prices.shape}) to csv took {end - start} seconds.')
_logs.info(f'CSV file size { os.path.getsize(stock_csv)*1e-6 } MB')

2026-10-19 01:53:03,412, 807204384.py, 7, INFO, Writing data ((225036, 9)) to csv took 1.3647856712341309 seconds.
2026-10-19 01:53:03,412, 807204384.py, 8, INFO, CSV file size 24.219179999999998 MB

## Save Data to Parquet

### Notes on Dask 

We could use Pandas to save the data directly into Parquet files. However, we will use a different approach by applying the [Dask framework](https://www.dask.org/). Dask provides functionality for working with datasets that do not fit in memory and parallelization to speed up computation. A few notes on Dask and Pandas:

- Pandas, Parquet, and Arrow:

    + We can work with large datasets and Parquet files in Pandas, but we will generally be limited by the amount of data that can fit in our computer's memory.
    + Pandas can write Parquet files using a PyArrow backend. In fact, recent versions of Pandas support PyArrow data types, and future versions will require a PyArrow backend. 
    + The PyArrow library is an interface between Python and the Apache Arrow project. In particular, the [Parquet data format](https://parquet.apache.org/) and [Arrow](https://arrow.apache.org/docs/python/parquet.html) are Apache projects.

- Dask 

    + Dask is much more than an interface to Arrow: Dask provides parallel and distributed computing on Pandas-like dataframes. 
    + Dask is also relatively easy to use as it mimics Pandas' API.
    + Dask allows us to work with larger datasets than Pandas. In a sense, it is an intermediate step between Pandas and big-data frameworks like Spark (or Databricks).
    + If you are familiar with Pandas, a good introduction is [10 Minutes to Dask](https://docs.dask.org/en/stable/10-minutes-to-dask.html).

In [10]:
import dask.dataframe as dd

parquet_dir = os.path.join(temp, "parquet")
shutil.rmtree(parquet_dir, ignore_errors=True)
os.makedirs(parquet_dir, exist_ok=True)

In [11]:
px_dd = dd.from_pandas(stock_prices, npartitions = len(select_tickers))

start = time.time()
px_dd.to_parquet(parquet_dir, engine = "pyarrow")
end = time.time()

_logs.info(f'Writing dd ({stock_prices.shape}) to parquet took {end - start} seconds.')
_logs.info(f'Parquet file size { get_dir_size(parquet_dir)*1e-6 } MB')

2026-10-19 01:53:10,482, 817812245.py, 7, INFO, Writing dd ((225036, 9)) to parquet took 0.6383464336395264 seconds.
2026-10-19 01:53:10,482, 817812245.py, 8, INFO, Parquet file size 8.518457 MB

### Pandas, Dask, and Parquet

The distinction of Pandas Dataframes, Dask Dataframes, and Parquet files is important:

+ Pandas dataframes combine the functionality of [NumPy](https://numpy.org/) (efficient vector operations, especially vector algebra) with a concise data manipulation framework that allows us to create columns of different data types (NumPy only allows single-type matrices), database-like operations (such as filtering rows, subsetting columns, and joining different dataframes).
+ Dask dataframes extend the functionality of Pandas dataframes beyond the confines of available memory and implement parallelized operations, among other benefits.
+ Parquet files are a file format. Parquet files can be created by Pandas and Dask, but Dask offers a superior interface. Parquet files are immutable: once written, they cannot be modified.
+ Parquet and Dask are not the same: Parquet is a file format that can be accessed by many applications and programming languages (Python, R, Power BI, etc.), while Dask is a Python package for working with large datasets using distributed computation.

### Dask is Powerful, but not Infallible

It is tempting to think of Dask as a super-Pandas, but each package has its advantages and disadvantages. 

+ Dask is not good at everything (see [Dask DataFrames Best Practices](https://docs.dask.org/en/stable/dataframe-best-practices.html)). 
+ A useful and somewhat idiosyncratic comparison of various data manipulation frameworks is shown below (from [DataFrames at Scale Comparison: TPC-H](https://docs.coiled.io/blog/tpch.html#when-to-use-duckdb-vs-polars-vs-dask-vs-spark)) 

Concept              | Spark | Dask | DuckDB | Polars
---------------------|-------|------|--------|--------
Fast Locally         | ❌    | 🤔  | ✅     | ✅
Fast on Cloud (1 TB) | ✅    | ✅  | ✅     | ❌
Fast on Cloud (10 TB)| ❌    | ✅  | ✅     | ❌
Scales Out           | ✅    | ✅  | ❌     | ❌
SQL                  | ✅    | 🤔  | ✅     | 🤔
More than SQL        | ✅    | ✅  | ❌     | ✅
Sensible Defaults    | ❌    | ✅  | ✅     | ✅


### Dask Best Practices

Parallelism brings extra complexity and overhead. Here are a few ideas to help you decide when to use Dask (from [Dask's Best Practices](https://docs.dask.org/en/stable/best-practices.html)):

#### Small is Better

+ Start small: if possible, use Pandas. Also, try to reduce your data using aggregation, then use Pandas.
+ More generally, NumPy, Pandas, and Scikit-Learn may have faster functions for what you need. Consult the relevant documentation, experiment, and/or consult with a colleague or expert.

#### Index with Care

+ Use the index: it is beneficial to have a well-defined index in Dask DataFrames, as it may speed up searching (filtering) the data. A one-dimensional index is allowed.
+ Minimize full-data shuffling as much as possible: indexing is an expensive operation. 

### Consider the Cost of Joins

+ Consider cases such as small-to-large joins, where the small dataframe fits in memory, but the large one does not. The small dataframe can be Pandas, while the larger one is a Dask dataframe.
+ Some joins are more expensive than others. 

    * Not expensive:

        - Join a Dask DataFrame with a Pandas DataFrame.
        - Join a Dask DataFrame with another Dask DataFrame of a single partition.
        - Join Dask DataFrames along their indexes.

    * Expensive:

        - Join Dask DataFrames along columns that are not their index.

# How Do We Store Prices?

+ We can store our data as a single blob. 

  - This can be difficult to maintain, especially because parquet files are immutable.
  - Using a single file, we would need to recreate the complete file any time that we update it.

+ An alternative strategy is to organize data files by ticker and date: 

  - We can create one file per ticker and month (or any other suitable frequency). 
  - Under this approach, we would only need to recreate the latest month's file at any update.

In [12]:
# Clean up before start
PRICE_DATA = os.getenv("PRICE_DATA")
import shutil
if os.path.exists(PRICE_DATA):
    shutil.rmtree(PRICE_DATA)

In [13]:
stock_prices.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume', 'source',
       'ticker'],
      dtype='str')

In [14]:
for ticker in stock_prices['ticker'].unique():
    # Filter data for ticker
    # Notice that these are Pandas dataframes
    _logs.info(f'Processing ticker: {ticker}')
    ticker_dt = stock_prices[stock_prices['ticker'] == ticker]
    ticker_dt = ticker_dt.assign(Year = ticker_dt.Date.dt.year)
    for yr in ticker_dt['Year'].unique():
        _logs.info(f'Processing year {yr} for ticker {ticker}.')
        # Filter data for year and convert to Dask dataframe
        yr_dd = dd.from_pandas(ticker_dt[ticker_dt['Year'] == yr],2)
        
        # Define path and create directories if not exist
        yr_path = os.path.join(PRICE_DATA, ticker, f"{ticker}_{yr}")
        os.makedirs(os.path.dirname(yr_path), exist_ok=True)
        _logs.info(f'Writing data to path: {yr_path}')

        # Write to Parquet
        yr_dd.to_parquet(yr_path, engine = "pyarrow")

2026-10-19 01:53:21,364, 2113979629.py, 4, INFO, Processing ticker: TOCA
2026-10-19 01:53:21,399, 2113979629.py, 8, INFO, Processing year 2017 for ticker TOCA.
2026-10-19 01:53:21,411, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/TOCA\TOCA_2017
2026-10-19 01:53:21,442, 2113979629.py, 8, INFO, Processing year 2018 for ticker TOCA.
2026-10-19 01:53:21,451, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/TOCA\TOCA_2018
2026-10-19 01:53:21,480, 2113979629.py, 8, INFO, Processing year 2019 for ticker TOCA.
2026-10-19 01:53:21,480, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/TOCA\TOCA_2019
2026-10-19 01:53:21,510, 2113979629.py, 8, INFO, Processing year 2020 for ticker TOCA.
2026-10-19 01:53:21,510, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/TOCA\TOCA_2020
2026-10-19 01:53:21,551, 2113979629.py, 4, INFO, Processing ticker: CBLI
2026-10-19 01:53:21,557, 2113979629.py, 8, INFO, Processing year 2006 for ticker CBLI.
2026-10-19 01:53:21,560, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CBLI\CBLI_2006
2026-10-19 01:53:21,577, 2113979629.py, 8, INFO, Processing year 2007 for ticker CBLI.
2026-10-19 01:53:21,599, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CBLI\CBLI_2007
2026-10-19 01:53:21,625, 2113979629.py, 8, INFO, Processing year 2008 for ticker CBLI.
2026-10-19 01:53:21,628, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CBLI\CBLI_2008
2026-10-19 01:53:21,657, 2113979629.py, 8, INFO, Processing year 2009 for ticker CBLI.
2026-10-19 01:53:21,667, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CBLI\CBLI_2009
2026-10-19 01:53:21,678, 2113979629.py, 8, INFO, Processing year 2010 for ticker CBLI.
2026-10-19 01:53:21,695, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CBLI\CBLI_2010
2026-10-19 01:53:21,710, 2113979629.py, 8, INFO, Processing year 2011 for ticker CBLI.
2026-10-19 01:53:21,729, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CBLI\CBLI_2011
2026-10-19 01:53:21,744, 2113979629.py, 8, INFO, Processing year 2012 for ticker CBLI.
2026-10-19 01:53:21,759, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CBLI\CBLI_2012
2026-10-19 01:53:21,785, 2113979629.py, 8, INFO, Processing year 2013 for ticker CBLI.
2026-10-19 01:53:21,791, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CBLI\CBLI_2013
2026-10-19 01:53:21,816, 2113979629.py, 8, INFO, Processing year 2014 for ticker CBLI.
2026-10-19 01:53:21,825, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CBLI\CBLI_2014
2026-10-19 01:53:21,853, 2113979629.py, 8, INFO, Processing year 2015 for ticker CBLI.
2026-10-19 01:53:21,860, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CBLI\CBLI_2015
2026-10-19 01:53:21,886, 2113979629.py, 8, INFO, Processing year 2016 for ticker CBLI.
2026-10-19 01:53:21,893, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CBLI\CBLI_2016
2026-10-19 01:53:21,921, 2113979629.py, 8, INFO, Processing year 2017 for ticker CBLI.
2026-10-19 01:53:21,928, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CBLI\CBLI_2017
2026-10-19 01:53:21,948, 2113979629.py, 8, INFO, Processing year 2018 for ticker CBLI.
2026-10-19 01:53:21,962, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CBLI\CBLI_2018
2026-10-19 01:53:21,985, 2113979629.py, 8, INFO, Processing year 2019 for ticker CBLI.
2026-10-19 01:53:21,992, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CBLI\CBLI_2019
2026-10-19 01:53:22,014, 2113979629.py, 8, INFO, Processing year 2020 for ticker CBLI.
2026-10-19 01:53:22,026, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CBLI\CBLI_2020
2026-10-19 01:53:22,042, 2113979629.py, 4, INFO, Processing ticker: ALGR
2026-10-19 01:53:22,042, 2113979629.py, 8, INFO, Processing year 2018 for ticker ALGR.
2026-10-19 01:53:22,062, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ALGR\ALGR_2018
2026-10-19 01:53:22,078, 2113979629.py, 8, INFO, Processing year 2019 for ticker ALGR.
2026-10-19 01:53:22,095, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ALGR\ALGR_2019
2026-10-19 01:53:22,117, 2113979629.py, 8, INFO, Processing year 2020 for ticker ALGR.
2026-10-19 01:53:22,125, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ALGR\ALGR_2020
2026-10-19 01:53:22,150, 2113979629.py, 4, INFO, Processing ticker: GLEO
2026-10-19 01:53:22,156, 2113979629.py, 8, INFO, Processing year 2019 for ticker GLEO.
2026-10-19 01:53:22,161, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/GLEO\GLEO_2019
2026-10-19 01:53:22,188, 2113979629.py, 8, INFO, Processing year 2020 for ticker GLEO.
2026-10-19 01:53:22,198, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/GLEO\GLEO_2020
2026-10-19 01:53:22,224, 2113979629.py, 4, INFO, Processing ticker: FLDM
2026-10-19 01:53:22,232, 2113979629.py, 8, INFO, Processing year 2011 for ticker FLDM.
2026-10-19 01:53:22,232, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/FLDM\FLDM_2011
2026-10-19 01:53:22,283, 2113979629.py, 8, INFO, Processing year 2012 for ticker FLDM.
2026-10-19 01:53:22,295, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/FLDM\FLDM_2012
2026-10-19 01:53:22,338, 2113979629.py, 8, INFO, Processing year 2013 for ticker FLDM.
2026-10-19 01:53:22,348, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/FLDM\FLDM_2013
2026-10-19 01:53:22,363, 2113979629.py, 8, INFO, Processing year 2014 for ticker FLDM.
2026-10-19 01:53:22,380, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/FLDM\FLDM_2014
2026-10-19 01:53:22,407, 2113979629.py, 8, INFO, Processing year 2015 for ticker FLDM.
2026-10-19 01:53:22,415, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/FLDM\FLDM_2015
2026-10-19 01:53:22,443, 2113979629.py, 8, INFO, Processing year 2016 for ticker FLDM.
2026-10-19 01:53:22,448, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/FLDM\FLDM_2016
2026-10-19 01:53:22,482, 2113979629.py, 8, INFO, Processing year 2017 for ticker FLDM.
2026-10-19 01:53:22,489, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/FLDM\FLDM_2017
2026-10-19 01:53:22,514, 2113979629.py, 8, INFO, Processing year 2018 for ticker FLDM.
2026-10-19 01:53:22,526, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/FLDM\FLDM_2018
2026-10-19 01:53:22,542, 2113979629.py, 8, INFO, Processing year 2019 for ticker FLDM.
2026-10-19 01:53:22,555, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/FLDM\FLDM_2019
2026-10-19 01:53:22,580, 2113979629.py, 8, INFO, Processing year 2020 for ticker FLDM.
2026-10-19 01:53:22,580, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/FLDM\FLDM_2020
2026-10-19 01:53:22,622, 2113979629.py, 4, INFO, Processing ticker: ETR
2026-10-19 01:53:22,625, 2113979629.py, 8, INFO, Processing year 1972 for ticker ETR.
2026-10-19 01:53:22,625, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_1972
2026-10-19 01:53:22,670, 2113979629.py, 8, INFO, Processing year 1973 for ticker ETR.
2026-10-19 01:53:22,682, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_1973
2026-10-19 01:53:22,705, 2113979629.py, 8, INFO, Processing year 1974 for ticker ETR.
2026-10-19 01:53:22,712, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_1974
2026-10-19 01:53:22,734, 2113979629.py, 8, INFO, Processing year 1975 for ticker ETR.
2026-10-19 01:53:22,744, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_1975
2026-10-19 01:53:22,761, 2113979629.py, 8, INFO, Processing year 1976 for ticker ETR.
2026-10-19 01:53:22,776, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_1976
2026-10-19 01:53:22,802, 2113979629.py, 8, INFO, Processing year 1977 for ticker ETR.
2026-10-19 01:53:22,815, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_1977
2026-10-19 01:53:22,836, 2113979629.py, 8, INFO, Processing year 1978 for ticker ETR.
2026-10-19 01:53:22,843, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_1978
2026-10-19 01:53:22,866, 2113979629.py, 8, INFO, Processing year 1979 for ticker ETR.
2026-10-19 01:53:22,872, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_1979
2026-10-19 01:53:22,897, 2113979629.py, 8, INFO, Processing year 1980 for ticker ETR.
2026-10-19 01:53:22,901, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_1980
2026-10-19 01:53:22,925, 2113979629.py, 8, INFO, Processing year 1981 for ticker ETR.
2026-10-19 01:53:22,930, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_1981
2026-10-19 01:53:22,957, 2113979629.py, 8, INFO, Processing year 1982 for ticker ETR.
2026-10-19 01:53:22,964, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_1982
2026-10-19 01:53:22,985, 2113979629.py, 8, INFO, Processing year 1983 for ticker ETR.
2026-10-19 01:53:22,994, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_1983
2026-10-19 01:53:23,015, 2113979629.py, 8, INFO, Processing year 1984 for ticker ETR.
2026-10-19 01:53:23,030, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_1984
2026-10-19 01:53:23,052, 2113979629.py, 8, INFO, Processing year 1985 for ticker ETR.
2026-10-19 01:53:23,058, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_1985
2026-10-19 01:53:23,078, 2113979629.py, 8, INFO, Processing year 1986 for ticker ETR.
2026-10-19 01:53:23,078, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_1986
2026-10-19 01:53:23,120, 2113979629.py, 8, INFO, Processing year 1987 for ticker ETR.
2026-10-19 01:53:23,125, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_1987
2026-10-19 01:53:23,147, 2113979629.py, 8, INFO, Processing year 1988 for ticker ETR.
2026-10-19 01:53:23,152, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_1988
2026-10-19 01:53:23,181, 2113979629.py, 8, INFO, Processing year 1989 for ticker ETR.
2026-10-19 01:53:23,181, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_1989
2026-10-19 01:53:23,220, 2113979629.py, 8, INFO, Processing year 1990 for ticker ETR.
2026-10-19 01:53:23,230, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_1990
2026-10-19 01:53:23,260, 2113979629.py, 8, INFO, Processing year 1991 for ticker ETR.
2026-10-19 01:53:23,269, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_1991
2026-10-19 01:53:23,301, 2113979629.py, 8, INFO, Processing year 1992 for ticker ETR.
2026-10-19 01:53:23,307, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_1992
2026-10-19 01:53:23,334, 2113979629.py, 8, INFO, Processing year 1993 for ticker ETR.
2026-10-19 01:53:23,343, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_1993
2026-10-19 01:53:23,367, 2113979629.py, 8, INFO, Processing year 1994 for ticker ETR.
2026-10-19 01:53:23,373, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_1994
2026-10-19 01:53:23,395, 2113979629.py, 8, INFO, Processing year 1995 for ticker ETR.
2026-10-19 01:53:23,402, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_1995
2026-10-19 01:53:23,426, 2113979629.py, 8, INFO, Processing year 1996 for ticker ETR.
2026-10-19 01:53:23,429, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_1996
2026-10-19 01:53:23,463, 2113979629.py, 8, INFO, Processing year 1997 for ticker ETR.
2026-10-19 01:53:23,469, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_1997
2026-10-19 01:53:23,491, 2113979629.py, 8, INFO, Processing year 1998 for ticker ETR.
2026-10-19 01:53:23,495, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_1998
2026-10-19 01:53:23,525, 2113979629.py, 8, INFO, Processing year 1999 for ticker ETR.
2026-10-19 01:53:23,532, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_1999
2026-10-19 01:53:23,545, 2113979629.py, 8, INFO, Processing year 2000 for ticker ETR.
2026-10-19 01:53:23,562, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_2000
2026-10-19 01:53:23,579, 2113979629.py, 8, INFO, Processing year 2001 for ticker ETR.
2026-10-19 01:53:23,594, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_2001
2026-10-19 01:53:23,613, 2113979629.py, 8, INFO, Processing year 2002 for ticker ETR.
2026-10-19 01:53:23,613, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_2002
2026-10-19 01:53:23,648, 2113979629.py, 8, INFO, Processing year 2003 for ticker ETR.
2026-10-19 01:53:23,660, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_2003
2026-10-19 01:53:23,681, 2113979629.py, 8, INFO, Processing year 2004 for ticker ETR.
2026-10-19 01:53:23,692, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_2004
2026-10-19 01:53:23,717, 2113979629.py, 8, INFO, Processing year 2005 for ticker ETR.
2026-10-19 01:53:23,723, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_2005
2026-10-19 01:53:23,748, 2113979629.py, 8, INFO, Processing year 2006 for ticker ETR.
2026-10-19 01:53:23,750, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_2006
2026-10-19 01:53:23,782, 2113979629.py, 8, INFO, Processing year 2007 for ticker ETR.
2026-10-19 01:53:23,788, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_2007
2026-10-19 01:53:23,812, 2113979629.py, 8, INFO, Processing year 2008 for ticker ETR.
2026-10-19 01:53:23,812, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_2008
2026-10-19 01:53:23,825, 2113979629.py, 8, INFO, Processing year 2009 for ticker ETR.
2026-10-19 01:53:23,842, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_2009
2026-10-19 01:53:23,864, 2113979629.py, 8, INFO, Processing year 2010 for ticker ETR.
2026-10-19 01:53:23,875, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_2010
2026-10-19 01:53:23,899, 2113979629.py, 8, INFO, Processing year 2011 for ticker ETR.
2026-10-19 01:53:23,906, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_2011
2026-10-19 01:53:23,930, 2113979629.py, 8, INFO, Processing year 2012 for ticker ETR.
2026-10-19 01:53:23,930, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_2012
2026-10-19 01:53:23,962, 2113979629.py, 8, INFO, Processing year 2013 for ticker ETR.
2026-10-19 01:53:23,969, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_2013
2026-10-19 01:53:23,977, 2113979629.py, 8, INFO, Processing year 2014 for ticker ETR.
2026-10-19 01:53:23,996, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_2014
2026-10-19 01:53:24,030, 2113979629.py, 8, INFO, Processing year 2015 for ticker ETR.
2026-10-19 01:53:24,037, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_2015
2026-10-19 01:53:24,058, 2113979629.py, 8, INFO, Processing year 2016 for ticker ETR.
2026-10-19 01:53:24,065, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_2016
2026-10-19 01:53:24,078, 2113979629.py, 8, INFO, Processing year 2017 for ticker ETR.
2026-10-19 01:53:24,097, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_2017
2026-10-19 01:53:24,108, 2113979629.py, 8, INFO, Processing year 2018 for ticker ETR.
2026-10-19 01:53:24,127, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_2018
2026-10-19 01:53:24,145, 2113979629.py, 8, INFO, Processing year 2019 for ticker ETR.
2026-10-19 01:53:24,152, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_2019
2026-10-19 01:53:24,179, 2113979629.py, 8, INFO, Processing year 2020 for ticker ETR.
2026-10-19 01:53:24,184, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/ETR\ETR_2020
2026-10-19 01:53:24,210, 2113979629.py, 4, INFO, Processing ticker: CMO
2026-10-19 01:53:24,213, 2113979629.py, 8, INFO, Processing year 1985 for ticker CMO.
2026-10-19 01:53:24,213, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CMO\CMO_1985
2026-10-19 01:53:24,250, 2113979629.py, 8, INFO, Processing year 1986 for ticker CMO.
2026-10-19 01:53:24,257, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CMO\CMO_1986
2026-10-19 01:53:24,283, 2113979629.py, 8, INFO, Processing year 1987 for ticker CMO.
2026-10-19 01:53:24,292, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CMO\CMO_1987
2026-10-19 01:53:24,316, 2113979629.py, 8, INFO, Processing year 1988 for ticker CMO.
2026-10-19 01:53:24,316, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CMO\CMO_1988
2026-10-19 01:53:24,351, 2113979629.py, 8, INFO, Processing year 1989 for ticker CMO.
2026-10-19 01:53:24,357, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CMO\CMO_1989
2026-10-19 01:53:24,381, 2113979629.py, 8, INFO, Processing year 1990 for ticker CMO.
2026-10-19 01:53:24,384, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CMO\CMO_1990
2026-10-19 01:53:24,413, 2113979629.py, 8, INFO, Processing year 1991 for ticker CMO.
2026-10-19 01:53:24,413, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CMO\CMO_1991
2026-10-19 01:53:24,448, 2113979629.py, 8, INFO, Processing year 1992 for ticker CMO.
2026-10-19 01:53:24,448, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CMO\CMO_1992
2026-10-19 01:53:24,478, 2113979629.py, 8, INFO, Processing year 1993 for ticker CMO.
2026-10-19 01:53:24,484, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CMO\CMO_1993
2026-10-19 01:53:24,503, 2113979629.py, 8, INFO, Processing year 1994 for ticker CMO.
2026-10-19 01:53:24,512, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CMO\CMO_1994
2026-10-19 01:53:24,528, 2113979629.py, 8, INFO, Processing year 1995 for ticker CMO.
2026-10-19 01:53:24,547, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CMO\CMO_1995
2026-10-19 01:53:24,569, 2113979629.py, 8, INFO, Processing year 1996 for ticker CMO.
2026-10-19 01:53:24,580, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CMO\CMO_1996
2026-10-19 01:53:24,603, 2113979629.py, 8, INFO, Processing year 1997 for ticker CMO.
2026-10-19 01:53:24,613, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CMO\CMO_1997
2026-10-19 01:53:24,636, 2113979629.py, 8, INFO, Processing year 1998 for ticker CMO.
2026-10-19 01:53:24,642, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CMO\CMO_1998
2026-10-19 01:53:24,661, 2113979629.py, 8, INFO, Processing year 1999 for ticker CMO.
2026-10-19 01:53:24,661, 2113979629.py, 15, INFO, Writing data to path: ../../05_src/data/prices/CMO\CMO_1999
2026-10-19 01:53:24,697, 2113979629.py, 8, INFO, Processing year 2000 for ticker CMO.

Why would we want to store data this way?

+ Data files are easier to maintain. We do not update old data, only recent data or the most recent "delta".
+ Parquet files, as long as they maintain a consistent schema, can all be read jointly.

# Load, Transform, and Save

In this section, we will load the Parquet files we generated, transform the data, and save the resulting dataset.

## Load

+ Parquet files can be read individually or as a collection.
+ `dd.read_parquet()` can take a list (collection) of files as input.
+ Use `glob` to obtain the collection of files.

In [15]:
from glob import glob

parquet_files = glob(os.path.join(PRICE_DATA, "**/*.parquet"), recursive = True)
_logs.info(f'Found {len(parquet_files)} parquet files for reading back into Dask.')

dd_px = dd.read_parquet(parquet_files).set_index("ticker")

2026-10-19 01:54:01,442, 174194153.py, 4, INFO, Found 1953 parquet files for reading back into Dask.

## Transform

+ This transformation step will create a *Features* data set. In our case, features will be stock returns (we obtained prices).
+ Dask dataframes work similarly to Pandas dataframes: in particular, we can perform groupby and apply operations.
+ Notice the use of [an anonymous (lambda) function](https://realpython.com/python-lambda/) in the apply statement.

In the code below, the following operation occurs:

+ Start with a Dask dataframe, `dd_px`.
+ Group the rows of this dataframe by the variable `ticker`, i.e., each group will contain the observations that pertain only to one ticker at a time. The `group_key` parameter controls whether an index entry is added with the value of the grouping variable (`ticker` in this case); if we made `group_keys=True`, we would have a duplicate `ticker` column.
+ For each group defined by a `ticker`, `apply()` the following calculation:

    - Sort the values by `Date` in ascending order.
    - Assign a new variable called `Close_lag_1` by shifting the position of the closing price (`Close`) by one position. The shift is written as a function of the *sorted* frame (`lambda df: df['Close'].shift(1)`). Writing `x['Close'].shift(1)` instead would shift the rows in their original, unsorted order: Dask does not guarantee that rows arrive sorted by date, so the lag would point to the wrong day.
    - Define the schema of the resulting dataframe (`meta`). We take it from `dd_px` itself and add the new `Close_lag_1` column, so the column types always match the data we loaded.

In [16]:
dd_px

Dask DataFrame Structure:
                          Date     Open     High      Low    Close Adj Close   Volume  source   Year
npartitions=60
ACRX            datetime64[us]  float64  float64  float64  float64   float64  float64  string  int32
ALGR                       ...      ...      ...      ...      ...       ...      ...     ...    ...
...                        ...      ...      ...      ...      ...       ...      ...     ...    ...
ZNH                        ...      ...      ...      ...      ...       ...      ...     ...    ...
ZNH                        ...      ...      ...      ...      ...       ...      ...     ...    ...
Dask Name: setindex, 2 expressions
Expr=SetIndex(frame=ReadParquetFSSpec(35ae2e3), _other='ticker', options={})

In [17]:
dd_shift = (
    dd_px
        .groupby('ticker', group_keys=False)
        .apply(
            lambda x: x.sort_values('Date', ascending = True)
                       .assign(Close_lag_1 = lambda df: df['Close'].shift(1)),
            meta = dd_px._meta.assign(Close_lag_1 = pd.Series(dtype = 'float64'))
    ))

Finally, using the dataframe that we created above, we can now `assign` the `Returns` variable to the entire dataset.

In [18]:
dd_rets = dd_shift.assign(
    Returns = lambda x: x['Close']/x['Close_lag_1'] - 1
)

Question: How do we know that we are not (erroneously) combining the last price of a ticker with the first price of the next ticker?

## Lazy Execution

What does `dd_rets` contain?

In [19]:
dd_rets

Dask DataFrame Structure:
                          Date     Open     High      Low    Close Adj Close   Volume  source   Year Close_lag_1  Returns
npartitions=60
ACRX            datetime64[us]  float64  float64  float64  float64   float64  float64  string  int32     float64  float64
ALGR                       ...      ...      ...      ...      ...       ...      ...     ...    ...         ...      ...
...                        ...      ...      ...      ...      ...       ...      ...     ...    ...         ...      ...
ZNH                        ...      ...      ...      ...      ...       ...      ...     ...    ...         ...      ...
ZNH                        ...      ...      ...      ...      ...       ...      ...     ...    ...         ...      ...
Dask Name: assign, 9 expressions
Expr=Assign(frame=Assign(frame=GroupByApply(frame=SetIndex(frame=ReadParquetFSSpec(35ae2e3), _other='ticker', options={}), observed=True, group_keys=False, func=<function <lambda> at 0x000001AF50500E00>, args=(), kwargs={})))

+ Dask is a lazy execution framework: commands will not execute until the computation is required. 
+ To trigger an execution in dask use `.compute()` or execute a command that requires the actual values (for example, write to Parquet or SQL).

In [20]:
dd_rets.compute()

,Date,Open,High,Low,Close,Adj Close,Volume,source,Year,Close_lag_1,Returns
ticker,,,,,,,,,,,
ACRX,2011-02-11,5.000000,5.090000,4.510000,4.550000,4.550000,1899700.0,ACRX.csv,2011,NaN,NaN
ACRX,2011-02-14,4.530000,4.730000,4.350000,4.380000,4.380000,66300.0,ACRX.csv,2011,4.550000,-0.037363
ACRX,2011-02-15,4.500000,4.500000,4.080000,4.310000,4.310000,37400.0,ACRX.csv,2011,4.380000,-0.015982
ACRX,2011-02-16,4.370000,4.370000,4.150000,4.240000,4.240000,9500.0,ACRX.csv,2011,4.310000,-0.016241
ACRX,2011-02-17,4.140000,4.220000,3.850000,3.850000,3.850000,60000.0,ACRX.csv,2011,4.240000,-0.091981
...,...,...,...,...,...,...,...,...,...,...,...
ZNH,2020-03-26,22.360001,23.200001,22.350000,23.200001,23.200001,51500.0,ZNH.csv,2020,21.940001,0.057429
ZNH,2020-03-27,21.400000,22.000000,21.120001,21.910000,21.910000,69700.0,ZNH.csv,2020,23.200001,-0.055603
ZNH,2020-03-30,21.500000,21.969999,20.510000,21.490000,21.490000,68800.0,ZNH.csv,2020,21.910000,-0.019169
ZNH,2020-03-31,21.799999,21.990000,21.500000,21.719999,21.719999,30900.0,ZNH.csv,2020,21.490000,0.010703
ZNH,2020-04-01,20.889999,21.190001,20.290001,20.389999,20.389999,33800.0,ZNH.csv,2020,21.719999,-0.061234

In [21]:
df = dd_rets.compute()
df.to_csv("test.csv")

In [22]:
df.head()

,Date,Open,High,Low,Close,Adj Close,Volume,source,Year,Close_lag_1,Returns
ticker,,,,,,,,,,,
ACRX,2011-02-11,5.00,5.09,4.51,4.55,4.55,1899700.0,ACRX.csv,2011,NaN,NaN
ACRX,2011-02-14,4.53,4.73,4.35,4.38,4.38,66300.0,ACRX.csv,2011,4.55,-0.037363
ACRX,2011-02-15,4.50,4.50,4.08,4.31,4.31,37400.0,ACRX.csv,2011,4.38,-0.015982
ACRX,2011-02-16,4.37,4.37,4.15,4.24,4.24,9500.0,ACRX.csv,2011,4.31,-0.016241
ACRX,2011-02-17,4.14,4.22,3.85,3.85,3.85,60000.0,ACRX.csv,2011,4.24,-0.091981

## Save

With our transformed data, we can now save the new feature to a Parquet file. We will need to answer the following questions depending on our context, setup, and available resources:

+ Should we keep the same namespace? 
+ Should we save all columns?

In [23]:
dd_rets

Dask DataFrame Structure:
                          Date     Open     High      Low    Close Adj Close   Volume  source   Year Close_lag_1  Returns
npartitions=60
ACRX            datetime64[us]  float64  float64  float64  float64   float64  float64  string  int32     float64  float64
ALGR                       ...      ...      ...      ...      ...       ...      ...     ...    ...         ...      ...
...                        ...      ...      ...      ...      ...       ...      ...     ...    ...         ...      ...
ZNH                        ...      ...      ...      ...      ...       ...      ...     ...    ...         ...      ...
ZNH                        ...      ...      ...      ...      ...       ...      ...     ...    ...         ...      ...
Dask Name: assign, 9 expressions
Expr=Assign(frame=Assign(frame=GroupByApply(frame=SetIndex(frame=ReadParquetFSSpec(35ae2e3), _other='ticker', options={}), observed=True, group_keys=False, func=<function <lambda> at 0x000001AF50500E00>, args=(), kwargs={})))

In [24]:
# Clean up before save
FEATURES_DATA = os.getenv("FEATURES_DATA")
if os.path.exists(FEATURES_DATA):
    shutil.rmtree(FEATURES_DATA)
dd_rets.to_parquet(FEATURES_DATA, 
                   overwrite = True, 
                   schema={
                       'Date': 'timestamp[ns]',
                       'Open': 'float64',
                       'High': 'float64',
                       'Low': 'float64',
                       'Close': 'float64',
                       'Adj Close': 'float64',
                       'Volume': 'int64',
                       'source': 'string',
                       'Year': 'int32',
                       'Close_lag_1': 'float64',
                       'Returns': 'float64',
                       'ticker': 'large_string'
                   })

# Optional: from Jupyter to Command Line

+ We have drafted our code in a Jupyter Notebook. 
+ Finalized code should be written in Python modules.

## Object Oriented vs Functional Programming

+ We can use classes to keep parameters and functions together.
+ We *could* use Object Oriented Programming, but parallelization of data manipulation and modelling tasks benefit from *Functional Programming*.
+ An Idea: 

    - [Data Oriented Programming](https://blog.klipse.tech/dop/2022/06/22/principles-of-dop.html).
    - Use the class to bundle together parameters and functions.
    - Use stateless operations and treat all data objects as immutable (we do not modify them, we overwrite them).
    - Take advantage of [`@staticmethod`](https://realpython.com/instance-class-and-static-methods-demystified/).

The code is in `../../05_src/stock_prices/data_manager.py`.

Our original design was:

![](./images/02_target_pipeline_manager.png)

In [25]:
from stock_prices.data_manager import DataManager
dm = DataManager()

Download all prices.

In [26]:
dm.process_sample_files()

2026-10-19 01:55:42,026, data_manager.py, 110, INFO, Processing sample of tickers
2026-10-19 01:55:42,029, data_manager.py, 117, INFO, Getting file list from ../../05_src/data/prices_csv/
2026-10-19 01:55:42,078, data_manager.py, 119, INFO, Found 8044 files in ../../05_src/data/prices_csv/
2026-10-19 01:55:42,079, data_manager.py, 126, INFO, Selecting sample of files
2026-10-19 01:55:42,080, data_manager.py, 132, INFO, Selected 30 files
2026-10-19 01:55:42,082, data_manager.py, 137, INFO, Processing file ../../05_src/data/prices_csv\stocks\XLNX.csv
2026-10-19 01:55:42,083, data_manager.py, 186, INFO, Reading file: ../../05_src/data/prices_csv\stocks\XLNX.csv
2026-10-19 01:55:42,114, data_manager.py, 155, INFO, Saving data by year
2026-10-19 01:55:42,116, data_manager.py, 157, INFO, Processing ticker: XLNX
2026-10-19 01:55:42,119, data_manager.py, 161, INFO, Processing year 1990 for ticker XLNX.
2026-10-19 01:55:42,126, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_1990
2026-10-19 01:55:42,157, data_manager.py, 161, INFO, Processing year 1991 for ticker XLNX.
2026-10-19 01:55:42,167, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_1991
2026-10-19 01:55:42,193, data_manager.py, 161, INFO, Processing year 1992 for ticker XLNX.
2026-10-19 01:55:42,199, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_1992
2026-10-19 01:55:42,228, data_manager.py, 161, INFO, Processing year 1993 for ticker XLNX.
2026-10-19 01:55:42,232, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_1993
2026-10-19 01:55:42,259, data_manager.py, 161, INFO, Processing year 1994 for ticker XLNX.
2026-10-19 01:55:42,265, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_1994
2026-10-19 01:55:42,297, data_manager.py, 161, INFO, Processing year 1995 for ticker XLNX.
2026-10-19 01:55:42,298, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_1995
2026-10-19 01:55:42,331, data_manager.py, 161, INFO, Processing year 1996 for ticker XLNX.
2026-10-19 01:55:42,331, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_1996
2026-10-19 01:55:42,365, data_manager.py, 161, INFO, Processing year 1997 for ticker XLNX.
2026-10-19 01:55:42,371, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_1997
2026-10-19 01:55:42,398, data_manager.py, 161, INFO, Processing year 1998 for ticker XLNX.
2026-10-19 01:55:42,407, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_1998
2026-10-19 01:55:42,434, data_manager.py, 161, INFO, Processing year 1999 for ticker XLNX.
2026-10-19 01:55:42,440, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_1999
2026-10-19 01:55:42,464, data_manager.py, 161, INFO, Processing year 2000 for ticker XLNX.
2026-10-19 01:55:42,471, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_2000
2026-10-19 01:55:42,498, data_manager.py, 161, INFO, Processing year 2001 for ticker XLNX.
2026-10-19 01:55:42,499, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_2001
2026-10-19 01:55:42,529, data_manager.py, 161, INFO, Processing year 2002 for ticker XLNX.
2026-10-19 01:55:42,541, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_2002
2026-10-19 01:55:42,561, data_manager.py, 161, INFO, Processing year 2003 for ticker XLNX.
2026-10-19 01:55:42,573, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_2003
2026-10-19 01:55:42,598, data_manager.py, 161, INFO, Processing year 2004 for ticker XLNX.
2026-10-19 01:55:42,601, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_2004
2026-10-19 01:55:42,630, data_manager.py, 161, INFO, Processing year 2005 for ticker XLNX.
2026-10-19 01:55:42,636, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_2005
2026-10-19 01:55:42,660, data_manager.py, 161, INFO, Processing year 2006 for ticker XLNX.
2026-10-19 01:55:42,663, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_2006
2026-10-19 01:55:42,697, data_manager.py, 161, INFO, Processing year 2007 for ticker XLNX.
2026-10-19 01:55:42,703, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_2007
2026-10-19 01:55:42,735, data_manager.py, 161, INFO, Processing year 2008 for ticker XLNX.
2026-10-19 01:55:42,743, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_2008
2026-10-19 01:55:42,773, data_manager.py, 161, INFO, Processing year 2009 for ticker XLNX.
2026-10-19 01:55:42,781, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_2009
2026-10-19 01:55:42,794, data_manager.py, 161, INFO, Processing year 2010 for ticker XLNX.
2026-10-19 01:55:42,813, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_2010
2026-10-19 01:55:42,828, data_manager.py, 161, INFO, Processing year 2011 for ticker XLNX.
2026-10-19 01:55:42,844, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_2011
2026-10-19 01:55:42,867, data_manager.py, 161, INFO, Processing year 2012 for ticker XLNX.
2026-10-19 01:55:42,874, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_2012
2026-10-19 01:55:42,920, data_manager.py, 161, INFO, Processing year 2013 for ticker XLNX.
2026-10-19 01:55:42,930, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_2013
2026-10-19 01:55:42,965, data_manager.py, 161, INFO, Processing year 2014 for ticker XLNX.
2026-10-19 01:55:42,972, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_2014
2026-10-19 01:55:42,992, data_manager.py, 161, INFO, Processing year 2015 for ticker XLNX.
2026-10-19 01:55:43,010, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_2015
2026-10-19 01:55:43,031, data_manager.py, 161, INFO, Processing year 2016 for ticker XLNX.
2026-10-19 01:55:43,047, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_2016
2026-10-19 01:55:43,057, data_manager.py, 161, INFO, Processing year 2017 for ticker XLNX.
2026-10-19 01:55:43,074, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_2017
2026-10-19 01:55:43,108, data_manager.py, 161, INFO, Processing year 2018 for ticker XLNX.
2026-10-19 01:55:43,111, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_2018
2026-10-19 01:55:43,140, data_manager.py, 161, INFO, Processing year 2019 for ticker XLNX.
2026-10-19 01:55:43,148, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_2019
2026-10-19 01:55:43,157, data_manager.py, 161, INFO, Processing year 2020 for ticker XLNX.
2026-10-19 01:55:43,176, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/XLNX\XLNX_2020
2026-10-19 01:55:43,193, data_manager.py, 137, INFO, Processing file ../../05_src/data/prices_csv\stocks\OTTR.csv
2026-10-19 01:55:43,193, data_manager.py, 186, INFO, Reading file: ../../05_src/data/prices_csv\stocks\OTTR.csv
2026-10-19 01:55:43,223, data_manager.py, 155, INFO, Saving data by year
2026-10-19 01:55:43,223, data_manager.py, 157, INFO, Processing ticker: OTTR
2026-10-19 01:55:43,223, data_manager.py, 161, INFO, Processing year 1973 for ticker OTTR.
2026-10-19 01:55:43,250, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_1973
2026-10-19 01:55:43,283, data_manager.py, 161, INFO, Processing year 1974 for ticker OTTR.
2026-10-19 01:55:43,290, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_1974
2026-10-19 01:55:43,317, data_manager.py, 161, INFO, Processing year 1975 for ticker OTTR.
2026-10-19 01:55:43,323, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_1975
2026-10-19 01:55:43,345, data_manager.py, 161, INFO, Processing year 1976 for ticker OTTR.
2026-10-19 01:55:43,358, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_1976
2026-10-19 01:55:43,379, data_manager.py, 161, INFO, Processing year 1977 for ticker OTTR.
2026-10-19 01:55:43,390, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_1977
2026-10-19 01:55:43,415, data_manager.py, 161, INFO, Processing year 1978 for ticker OTTR.
2026-10-19 01:55:43,422, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_1978
2026-10-19 01:55:43,444, data_manager.py, 161, INFO, Processing year 1979 for ticker OTTR.
2026-10-19 01:55:43,444, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_1979
2026-10-19 01:55:43,477, data_manager.py, 161, INFO, Processing year 1980 for ticker OTTR.
2026-10-19 01:55:43,485, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_1980
2026-10-19 01:55:43,515, data_manager.py, 161, INFO, Processing year 1981 for ticker OTTR.
2026-10-19 01:55:43,528, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_1981
2026-10-19 01:55:43,561, data_manager.py, 161, INFO, Processing year 1982 for ticker OTTR.
2026-10-19 01:55:43,567, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_1982
2026-10-19 01:55:43,595, data_manager.py, 161, INFO, Processing year 1983 for ticker OTTR.
2026-10-19 01:55:43,601, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_1983
2026-10-19 01:55:43,612, data_manager.py, 161, INFO, Processing year 1984 for ticker OTTR.
2026-10-19 01:55:43,631, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_1984
2026-10-19 01:55:43,642, data_manager.py, 161, INFO, Processing year 1985 for ticker OTTR.
2026-10-19 01:55:43,661, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_1985
2026-10-19 01:55:43,677, data_manager.py, 161, INFO, Processing year 1986 for ticker OTTR.
2026-10-19 01:55:43,690, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_1986
2026-10-19 01:55:43,713, data_manager.py, 161, INFO, Processing year 1987 for ticker OTTR.
2026-10-19 01:55:43,724, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_1987
2026-10-19 01:55:43,747, data_manager.py, 161, INFO, Processing year 1988 for ticker OTTR.
2026-10-19 01:55:43,762, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_1988
2026-10-19 01:55:43,784, data_manager.py, 161, INFO, Processing year 1989 for ticker OTTR.
2026-10-19 01:55:43,790, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_1989
2026-10-19 01:55:43,810, data_manager.py, 161, INFO, Processing year 1990 for ticker OTTR.
2026-10-19 01:55:43,810, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_1990
2026-10-19 01:55:43,845, data_manager.py, 161, INFO, Processing year 1991 for ticker OTTR.
2026-10-19 01:55:43,852, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_1991
2026-10-19 01:55:43,874, data_manager.py, 161, INFO, Processing year 1992 for ticker OTTR.
2026-10-19 01:55:43,880, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_1992
2026-10-19 01:55:43,915, data_manager.py, 161, INFO, Processing year 1993 for ticker OTTR.
2026-10-19 01:55:43,921, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_1993
2026-10-19 01:55:43,943, data_manager.py, 161, INFO, Processing year 1994 for ticker OTTR.
2026-10-19 01:55:43,943, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_1994
2026-10-19 01:55:43,975, data_manager.py, 161, INFO, Processing year 1995 for ticker OTTR.
2026-10-19 01:55:43,978, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_1995
2026-10-19 01:55:44,010, data_manager.py, 161, INFO, Processing year 1996 for ticker OTTR.
2026-10-19 01:55:44,011, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_1996
2026-10-19 01:55:44,040, data_manager.py, 161, INFO, Processing year 1997 for ticker OTTR.
2026-10-19 01:55:44,040, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_1997
2026-10-19 01:55:44,073, data_manager.py, 161, INFO, Processing year 1998 for ticker OTTR.
2026-10-19 01:55:44,078, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_1998
2026-10-19 01:55:44,095, data_manager.py, 161, INFO, Processing year 1999 for ticker OTTR.
2026-10-19 01:55:44,111, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_1999
2026-10-19 01:55:44,134, data_manager.py, 161, INFO, Processing year 2000 for ticker OTTR.
2026-10-19 01:55:44,140, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_2000
2026-10-19 01:55:44,160, data_manager.py, 161, INFO, Processing year 2001 for ticker OTTR.
2026-10-19 01:55:44,160, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_2001
2026-10-19 01:55:44,190, data_manager.py, 161, INFO, Processing year 2002 for ticker OTTR.
2026-10-19 01:55:44,190, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_2002
2026-10-19 01:55:44,228, data_manager.py, 161, INFO, Processing year 2003 for ticker OTTR.
2026-10-19 01:55:44,228, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_2003
2026-10-19 01:55:44,260, data_manager.py, 161, INFO, Processing year 2004 for ticker OTTR.
2026-10-19 01:55:44,273, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_2004
2026-10-19 01:55:44,290, data_manager.py, 161, INFO, Processing year 2005 for ticker OTTR.
2026-10-19 01:55:44,309, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_2005
2026-10-19 01:55:44,341, data_manager.py, 161, INFO, Processing year 2006 for ticker OTTR.
2026-10-19 01:55:44,349, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_2006
2026-10-19 01:55:44,374, data_manager.py, 161, INFO, Processing year 2007 for ticker OTTR.
2026-10-19 01:55:44,374, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_2007
2026-10-19 01:55:44,411, data_manager.py, 161, INFO, Processing year 2008 for ticker OTTR.
2026-10-19 01:55:44,414, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_2008
2026-10-19 01:55:44,445, data_manager.py, 161, INFO, Processing year 2009 for ticker OTTR.
2026-10-19 01:55:44,451, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_2009
2026-10-19 01:55:44,474, data_manager.py, 161, INFO, Processing year 2010 for ticker OTTR.
2026-10-19 01:55:44,474, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_2010
2026-10-19 01:55:44,508, data_manager.py, 161, INFO, Processing year 2011 for ticker OTTR.
2026-10-19 01:55:44,516, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_2011
2026-10-19 01:55:44,548, data_manager.py, 161, INFO, Processing year 2012 for ticker OTTR.
2026-10-19 01:55:44,554, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_2012
2026-10-19 01:55:44,576, data_manager.py, 161, INFO, Processing year 2013 for ticker OTTR.
2026-10-19 01:55:44,576, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_2013
2026-10-19 01:55:44,607, data_manager.py, 161, INFO, Processing year 2014 for ticker OTTR.
2026-10-19 01:55:44,607, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_2014
2026-10-19 01:55:44,643, data_manager.py, 161, INFO, Processing year 2015 for ticker OTTR.
2026-10-19 01:55:44,644, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_2015
2026-10-19 01:55:44,663, data_manager.py, 161, INFO, Processing year 2016 for ticker OTTR.
2026-10-19 01:55:44,680, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_2016
2026-10-19 01:55:44,692, data_manager.py, 161, INFO, Processing year 2017 for ticker OTTR.
2026-10-19 01:55:44,712, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_2017
2026-10-19 01:55:44,733, data_manager.py, 161, INFO, Processing year 2018 for ticker OTTR.
2026-10-19 01:55:44,740, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_2018
2026-10-19 01:55:44,760, data_manager.py, 161, INFO, Processing year 2019 for ticker OTTR.
2026-10-19 01:55:44,774, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_2019
2026-10-19 01:55:44,790, data_manager.py, 161, INFO, Processing year 2020 for ticker OTTR.
2026-10-19 01:55:44,807, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/OTTR\OTTR_2020
2026-10-19 01:55:44,829, data_manager.py, 137, INFO, Processing file ../../05_src/data/prices_csv\stocks\EXEL.csv
2026-10-19 01:55:44,829, data_manager.py, 186, INFO, Reading file: ../../05_src/data/prices_csv\stocks\EXEL.csv
2026-10-19 01:55:44,865, data_manager.py, 155, INFO, Saving data by year
2026-10-19 01:55:44,865, data_manager.py, 157, INFO, Processing ticker: EXEL
2026-10-19 01:55:44,865, data_manager.py, 161, INFO, Processing year 2000 for ticker EXEL.
2026-10-19 01:55:44,877, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/EXEL\EXEL_2000
2026-10-19 01:55:44,906, data_manager.py, 161, INFO, Processing year 2001 for ticker EXEL.
2026-10-19 01:55:44,907, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/EXEL\EXEL_2001
2026-10-19 01:55:44,927, data_manager.py, 161, INFO, Processing year 2002 for ticker EXEL.
2026-10-19 01:55:44,944, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/EXEL\EXEL_2002
2026-10-19 01:55:44,960, data_manager.py, 161, INFO, Processing year 2003 for ticker EXEL.
2026-10-19 01:55:44,976, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/EXEL\EXEL_2003
2026-10-19 01:55:45,005, data_manager.py, 161, INFO, Processing year 2004 for ticker EXEL.
2026-10-19 01:55:45,013, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/EXEL\EXEL_2004
2026-10-19 01:55:45,043, data_manager.py, 161, INFO, Processing year 2005 for ticker EXEL.
2026-10-19 01:55:45,050, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/EXEL\EXEL_2005
2026-10-19 01:55:45,073, data_manager.py, 161, INFO, Processing year 2006 for ticker EXEL.
2026-10-19 01:55:45,076, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/EXEL\EXEL_2006
2026-10-19 01:55:45,093, data_manager.py, 161, INFO, Processing year 2007 for ticker EXEL.
2026-10-19 01:55:45,110, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/EXEL\EXEL_2007
2026-10-19 01:55:45,126, data_manager.py, 161, INFO, Processing year 2008 for ticker EXEL.
2026-10-19 01:55:45,126, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/EXEL\EXEL_2008
2026-10-19 01:55:45,160, data_manager.py, 161, INFO, Processing year 2009 for ticker EXEL.
2026-10-19 01:55:45,160, data_manager.py, 165, INFO, Writing data to path: ../../05_src/data/prices/EXEL\EXEL_2009
2026-10-19 01:55:45,193, data_manager.py, 161, INFO, Processing year 2010 for ticker EXEL.

Finally, add features to the data set and save to a *feature store*.

In [27]:
dm.featurize()

2026-10-19 01:56:22,824, data_manager.py, 200, INFO, Creating features data.
2026-10-19 01:56:22,827, data_manager.py, 207, INFO, Loading price data from ../../05_src/data/prices/
2026-10-19 01:56:23,384, data_manager.py, 238, INFO, Saving features to ../../05_src/data/features/stock_features